- name: Install postgresql
  community.general.pacman:
    name: postgresql
    update_cache: true

- name: Disable Copy-on-Write
  ansible.builtin.file:
    path: "{{ host.postgresql.dir }}"
    attributes: C
    recurse: true

- name: Setup postgresql
  ansible.builtin.command: initdb --locale {{ host.system.locale }} -E {{ host.system.charset }} -D {{ host.postgresql.dir }}/data
  changed_when: true
  become: true
  become_user: postgres

- name: Start postgresql service
  ansible.builtin.systemd:
    state: started
    name: postgresql
    enabled: true

- name: Set superuser
  ansible.builtin.command: createuser --superuser {{ host.user.wheel.name }}
  changed_when: true
  become: true
  become_user: postgres

- name: Create superuser database
  ansible.builtin.command: createdb {{ host.user.wheel.name }}
  changed_when: true
  become: true
  become_user: postgres
