- name: Install package
  community.general.pacman:
    name: nginx
    update_cache: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/nginx/
    mode: "0644"
  with_items:
    - nginx.conf
    - conf.d

- name: Copy files configuration
  ansible.builtin.template:
    src: files.conf.j2
    dest: /etc/nginx/conf.d/files.conf
    mode: "0644"

- name: Start nginx service
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: true
