---
secrets:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost
    dhj-laptop:
    node01:
    node02:
    node03:
    node04:
    vagrant-node-01:
all:
  children:
    workstations:
      hosts:
        local:
        dhj-laptop:
    truenas:
      hosts:
        node01:
        node02:
        node03:
        node04:
        vagrant-node-01: