---
secrets:
  hosts:
    dhj-laptop:
      ansible_connection: local
    node01:
    node02:
    node03:
    node04:
all:
  children:
    workstations:
      hosts:
        dhj-laptop:
    truenas:
      hosts:
        node01:
        node02:
        node03:
        node04: