collections:
  - name: kewlfft.aur
    version: 0.13.0
  - name: community.general
    version: 11.4.1
  - name: ansible.posix
    version: 2.1.0
  - name: arensb.truenas
    version: 1.12.0
roles:
  - name: geerlingguy.docker
    version: 7.8.0