- name: Truenas
  hosts:
    - node-01
    - node-02
    - node-03
    - node-04
  gather_facts: true
  roles:
    - { role: truenas, tags: truenas }
  become: true

- name: Laptop
  hosts:
    - dhj-laptop
  gather_facts: true
  roles:
    - { role: disk, tags: disk }
    - { role: boot, tags: boot }
    - { role: alsa, tags: alsa }
    - { role: system_extra, tags: system }
    - { role: geerlingguy.docker, tags: docker }
    - { role: docker, tags: docker }
    - { role: virtualization, tags: virt}
    - { role: program, tags: program }
    - { role: desktop, tags: desktop }
    - { role: cups, tags: cups }
  become: true
