- name: Install package
  community.general.pacman:
    name: git
    update_cache: true

# - name: Copy configuration files
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: /home/{{ host.user.wheel.name }}/
#     mode: "0644"
#     group: "{{ host.user.wheel.name }}"
#     owner: "{{ host.user.wheel.name }}"
#   with_items:
#     - .gitconfig
#     - .bash_login.d
