- name: Install packages
  community.general.pacman:
    name:
      - mosquitto
    update_cache: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/
    mode: "0644"

- name: Create congfiguration directory
  ansible.builtin.file:
    path: /etc/mosquitto/conf.d
    state: directory
    mode: "0755"

- name: Copy custom congfiguration
  ansible.builtin.copy:
    src: conf.d
    dest: /etc/mosquitto/
    mode: "0644"

- name: Restore copy
  ansible.builtin.unarchive:
    src: "{{ host.mosquitto.backup }}"
    dest: /etc/mosquitto/
    remote_src: true

- name: Start mosquito systemd service
  ansible.builtin.systemd:
    state: started
    name: mosquitto
    enabled: true
