- name: Install package
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
    update_cache: true

  notify:
    - reboot

- name: Wait for restart
  ansible.builtin.pause:

- name: Add host network adapter
  ansible.builtin.command: vboxmanage hostonlyif create
  changed_when: true
