- name: Install package
  community.general.pacman:
    name:
      - tmux
    update_cache: true

- name: Copy configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ host.user.wheel.name }}/
    mode: "0644"
    group: "{{ host.user.wheel.name }}"
    owner: "{{ host.user.wheel.name }}"
  with_items:
    - .config
    - .bashrc.d
    - .tmux.conf
    - .tmux

- name: Copy bin files
  ansible.builtin.copy:
    src: bin
    dest: /home/{{ host.user.wheel.name }}/
    mode: "0755"
    group: "{{ host.user.wheel.name }}"
    owner: "{{ host.user.wheel.name }}"

- name: Enable tmux service
  become: true
  become_user: "{{ host.user.wheel.name }}"
  become_method: community.general.machinectl
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    scope: user
    name: tmux
    enabled: true

- name: Fix permissions
  ansible.builtin.file:
    path: /home/{{ host.user.wheel.name }}/.tmux
    owner: "{{ host.user.wheel.name }}"
    group: "{{ host.user.wheel.name }}"
    recurse: true
    mode: "0755"
