- name: Remove packages
  community.general.pacman:
    name:
      - vim
    state: absent
    extra_args: --recursive

- name: Install package
  community.general.pacman:
    name: gvim
    update_cache: true
    extra_args: --noconfirm

- name: Copy vimrc plugins
  ansible.builtin.copy:
    src: .vim
    dest: /home/{{ host.user.wheel.name }}/
    mode: "0644"
    group: "{{ host.user.wheel.name }}"
    owner: "{{ host.user.wheel.name }}"

- name: Install submodules
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: /home/{{ host.user.wheel.name }}/.vim/pack/vendor/start/{{ item | regex_search('[^/]+(?=.git)') }}
    force: true
    version: master
  with_items: "{{ host.vim.plugins }}"

- name: Fix permissions
  ansible.builtin.file:
    path: /home/{{ host.user.wheel.name }}/.vim
    owner: "{{ host.user.wheel.name }}"
    group: "{{ host.user.wheel.name }}"
    recurse: true
    mode: "0755"

- name: Set EDITOR
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: EDITOR=vim
