- name: Copy docker configuration
  ansible.builtin.copy:
    src: docker
    dest: /etc/
    mode: "0644"

- name: Copy docker systemd file
  ansible.builtin.copy:
    src: fava.service
    dest: /usr/local/lib/systemd/system/
    mode: "0644"

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/fava.conf
    mode: "0644"

- name: Create configuration directory
  ansible.builtin.file:
    path: /var/lib/fava/
    state: directory
    mode: "0755"

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Start systemd service
  ansible.builtin.systemd:
    state: started
    name: fava
    enabled: true
