- name: Install package
  community.general.pacman:
    name: aria2
    update_cache: true

- name: Copy configuration files
  ansible.builtin.template:
    src: aria2.conf.j2
    dest: /etc/aria2.conf
    mode: "0644"

- name: Ensure session file exists
  ansible.builtin.file:
    path: "{{ host.aria2.dir }}/aria2.session"
    state: touch
    mode: "0644"

- name: Copy systemd unit file
  ansible.builtin.copy:
    src: aria.service
    dest: /usr/local/lib/systemd/system/
    mode: "0644"

- name: Start aria service
  ansible.builtin.systemd:
    state: started
    name: aria2
    enabled: true
    daemon_reload: true

- name: Install frontend
  ansible.builtin.git:
    repo: https://github.com/ziahamza/webui-aria2.git
    dest: /usr/share/nginx/aria2
    depth: 1
    version: master

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/aria2.conf
    mode: "0644"

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
