---
- name: Install linters
  community.general.pacman:
    name:
      - actionlint
      - ansible-lint
      - gh
      - jq
      - jre-openjdk
      - python-cfn-lint
      - ruff
      - shellcheck
      - yamlfmt
      - yamllint
    update_cache: true

- name: Install asdf
  ansible.builtin.git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.asdf
    version: master
  with_items: '{{ host.program.asdf.git }}'

- name: Install plugins
  ansible.builtin.git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.asdf/plugins/{{ item | regex_search('[^/asdf-]+(?=.git)') }}
    depth: 1
    version: master
  with_items: '{{ host.program.asdf.plugins }}'

- name: Copy configuration files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .asdfrc
    - .bash_login.d
    - .config
    - eslint.config.mjs
    - .gemrc
    - .rspec
    - .rubocop.yml
    - .shellcheckrc

- name: Fix permissions
  ansible.builtin.file:
    path: /home/{{ host.user.wheel.name }}/.asdf
    owner: '{{ host.user.wheel.name }}'
    group: '{{ host.user.wheel.name }}'
    recurse: true
